### ISSUE TITLE
Option to redirect log output to stdout

### ISSUE THREAD

**Issue by flit** [mbedmicro/pyOCD#523]
Add session option that lets the user choose whether log output is written to stderr (default) or stdout.

The reason for this is that stderr output appears in the Eclipse console view as red text by default (though customizable via a preference). Some users apparently find this confusing and want black text (stdout) instead, without having to modify preferences.

**Comment by flit** [comment]
Note that if you really want this, you can use logging configuration to accomplish it.

Just use a `logging` key in a config file that looks like the example below. It overrides the root log handler with one that writes to stdout.

```yaml
logging:
  formatters:
    brief:
      format: '%(relativeCreated)07d - %(levelname)s - %(name)s - %(message)s'
  handlers:
    console:
      class: logging.StreamHandler
      formatter: brief   # reference to "brief" formatter above
      level: DEBUG
      stream: ext://sys.stdout
  root:
    level: INFO
    handlers:
      - console          # reference to "console" handler above
  loggers:
    pyocd:
      level: INFO        # set all pyocd loggers to INFO level
    pyocd.core.coresight_target:
      level: DEBUG       # set this logger to DEBUG level
```
